apiVersion: v1
kind: Pod
metadata:
  name: centos
  labels:
    k8s-app: centos7
    version: v1
    kubernetes.io/cluster-service: "true"
  annotations:
    - name: String
spec:
  restartPolicy: Always
  nodeSelector:
    zone: node1
  containers:
    - name: centos7
    image:
