version: '2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    networks:
       elk:
          ipv4_address: 192.168.30.21
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /etc/docker/elk/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:6.2.2
    networks:
       elk:
          ipv4_address: 192.168.29.22
    ports:
      - "5044:5044"
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elasticsearch
    volumes:
      - /etc/docker/elk/conf/logstash.yml:/usr/share/logstash/config/logstash.yml
      - /etc/docker/elk/conf/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.2
    networks:
       elk:
          ipv4_address: 192.168.30.23
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    volumes:
      - /etc/docker/elk/conf/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    networks:
      - elk

networks:
  elk:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.30.0/26