version: '2'
services:
  hadoop-master:
    build:.
    networks:
      hanet:
        ipv4_address: 192.168.29.21
    container_name: hadoop-master
    expose:
        - 22
        - 2122
        - 8000
        - 8030
        - 8031
        - 8032
        - 8033
        - 8040
        - 8042
        - 8080
        - 8088
        - 9000
        - 19888
        - 49707
        - 50010
        - 50020
        - 50070
        - 50075
        - 50090
    ports:
      - 8088:8088
    extra_hosts:
     - "master:192.168.29.21"
     - "salve1:192.168.29.22"
     - "salve2:192.168.29.23"
  hadoop-salve1:
    build:.
    networks:
       hanet:
          ipv4_address: 192.168.29.22
    container_name: hadoop-salve1
    expose:
        - 22
        - 2122
        - 8000
        - 8030
        - 8031
        - 8032
        - 8033
        - 8040
        - 8042
        - 8080
        - 8088
        - 9000
        - 19888
        - 49707
        - 50010
        - 50020
        - 50070
        - 50075
        - 50090
      ports:
        - 8088:8088
      extra_hosts:
     - "master:192.168.29.21"
     - "salve1:192.168.29.22"
     - "salve2:192.168.29.23"
  hadoop-salve2:
    build:.
    networks:
       hanet:
          ipv4_address: 192.168.29.23
    container_name: hadoop-salve2
    expose:
        - 22
        - 2122
        - 8000
        - 8030
        - 8031
        - 8032
        - 8033
        - 8040
        - 8042
        - 8080
        - 8088
        - 9000
        - 19888
        - 49707
        - 50010
        - 50020
        - 50070
        - 50075
        - 50090
      ports:
        - 8088:8088
      extra_hosts:
     - "master:192.168.29.21"
     - "salve1:192.168.29.22"
     - "salve2:192.168.29.23"

networks:
  hanet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.29.0/26
